site_name: Shoug's Digital Garden
site_url: https://shoug-alomran.github.io/My-Garden/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - search.suggest
    - navigation.instant
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/leaf
  font:
    text: Inter
    code: Fira Code

nav:
  - Home: index.md
  - Software Engineering:
      - Intro: software-engineering/Intro.md
      - SE201:
          - Chapter 5 - Diagram Symbols: "software-engineering/SE201/Chapter 5 - Diagram Sybmols.md"
      - CS285:
          - Number Theory and Cryptography: "software-engineering/CS285/Number Theory and Cryptography.md"
          - Basic Structures: "software-engineering/CS285/Basic Structures.md"
          - Mathematical Induction and Recursion: "software-engineering/CS285/Mathematical Induction and Recursion.md"
      - CS210:
          - Lists: "software-engineering/CS210/Lists.md"
          - Trees: "software-engineering/CS210/Trees.md"
          - AVL: "software-engineering/CS210/AVL.md"
          - Heaps: "software-engineering/CS210/Heaps.md"
          - Hash Tables: "software-engineering/CS210/Hash Tables.md"
          - BST: "software-engineering/CS210/BST.html"
          - Recursion: "software-engineering/CS210/Recursion.md"
          - Quick Sort: "software-engineering/CS210/Quick Sort.md"
          - Merge Sort: "software-engineering/CS210/Merge Sort.md"
          - Heaps: "software-engineering/CS210/Heaps.md"
          - Stacks and Queues: "software-engineering/CS210/Stacks and Queues.md"
  - Cyber Security:
      - Intro: cyber-security/Intro.md
  - Career Development:
      - Projects: "Career Development/projects.md"
      - Me: "Career Development/me.md"
  - Links: links.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.inlinehilite

plugins:
  - search