site_name: Shoug's Digital Garden
site_url: https://shoug-tech.com

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/leaf
  font:
    text: Inter
    code: Fira Code

nav:
  - Home: index.md
  - Software Engineering:
      - Intro: software-engineering/Intro.md
      - SE201:
          - Chapter 1 - Software Engineering Practices and Ethics: "software-engineering/SE201/Software Engineering Practices and Ethics.md"
          - Chapter 1 Quiz: "software-engineering/SE201/Chapter 1 Quiz.md"
          - Chapter 2 - Software Processes: "software-engineering/SE201/Software Processes.md"
          - Chapter 2 Quiz: "software-engineering/SE201/Chapter 2 Quiz.md"
          - Chapter 3 - Agile Software Engineering: "software-engineering/SE201/Agile Software Engineering.md"
          - Chapter 3 Quiz: "software-engineering/SE201/Chapter 3 Quiz.md"
          - Chapter 4 - Software Project Management: "software-engineering/SE201/Software Project Management.md"
          - Chapter 4 Quiz: "software-engineering/SE201/Chapter 4 Quiz.md"
          - Chapter 5 - Requirements Engineering: "software-engineering/SE201/Requirements Engineering.md"
          - Chapter 5 - Diagram Symbols: "software-engineering/SE201/Chapter 5 - Diagram Sybmols.md"
          - Complete UML & Software Engineering Diagrams Guide: "software-engineering/SE201/Complete UML & Software Engineering Diagrams Guide.md"
          - Chapter 5 Quiz: "software-engineering/SE201/Chapter 5 Quiz.md"
          - Chapter 6 - Software Design : "software-engineering/SE201/Software Design.md"
          - Chapter 6 Quiz: "software-engineering/SE201/Chapter 6 Quiz.md"
          - Chapter 7 - Software Construction : "software-engineering/SE201/Software Construction.md"
          - Chapter 7 Quiz: "software-engineering/SE201/Chapter 7 Quiz.md"
          - Chapter 8 - Software Testing : "software-engineering/SE201/Software Testing.md"
          - Chapter 8 Quiz: "software-engineering/SE201/Chapter 8 Quiz.md"
          - Cheat Sheet: "software-engineering/SE201/Cheat Sheet.md"
          - Compiled MCQs: "software-engineering/SE201/Compiled MCQs.md"

      - CS285:
          - Logic and Proof: "software-engineering/CS285/Logic and Proof.md"
          - Number Theory and Cryptography: "software-engineering/CS285/Number Theory and Cryptography.md"
          - Basic Structures: "software-engineering/CS285/Basic Structures.md"
          - Mathematical Induction and Recursion: "software-engineering/CS285/Mathematical Induction and Recursion.md"
          - Counting: "software-engineering/CS285/Counting.md"
          - Advanced Counting: "software-engineering/CS285/Advanced Counting.md"
          - Relations: "software-engineering/CS285/Relations.md"
          - Cheat Sheet: "software-engineering/CS285/Cheat Sheet.md"

      - CS210:
          - Lists: "software-engineering/CS210/Lists.md"
          - Trees: "software-engineering/CS210/Trees.md"
          - AVL: "software-engineering/CS210/AVL.md"
          - Heaps: "software-engineering/CS210/Heaps.md"
          - Hash Tables: "software-engineering/CS210/Hash Tables.md"
          - BST: "software-engineering/CS210/BST.md"
          - Recursion: "software-engineering/CS210/Recursion.md"
          - Quick Sort: "software-engineering/CS210/Quick Sort.md"
          - Merge Sort: "software-engineering/CS210/Merge Sort.md"
          - Stacks and Queues: "software-engineering/CS210/Stacks and Queues.md"
          - Cheat Sheet: "software-engineering/CS210/Cheat Sheet.md"
          - Cheat Sheet_2: "software-engineering/CS210/Cheat Sheet_2.md"

      - CS330:
          - Chapter 1 - Introduction to Databases: "software-engineering/CS330/Chapter 1.md"
          - Chapter 2 - Operating System Structures: "software-engineering/CS330/Chapter 2.md"
          - Chapter 3 - Processes: "software-engineering/CS330/Chapter 3.md"
          - Chapter 4 - Threads: "software-engineering/CS330/Chapter 4.md"
          - Chapter 5 - CPU Scheduling: "software-engineering/CS330/Chapter 5.md"
          - Chapter 6 - Process Synchronization: "software-engineering/CS330/Chapter 6.md"
          - Chapter 7 - Deadlocks: "software-engineering/CS330/Chapter 7.md"
          - Chapter 8 - Main Memory Management: "software-engineering/CS330/Chapter 8.md"
          - Chapter 9 - Virtual Memory: "software-engineering/CS330/Chapter 9.md"

      - CS340:
          - Chapter 1 - Introduction to Databases: "software-engineering/CS340/Chapter 1.md"

      - SE311:
          - Chapter 1 - Software Requirements Engineering: "software-engineering/SE311/Chapter 1.md"
          - Chapter 1 Quiz: "software-engineering/SE311/Chapter 1 Quiz.md"
  - Cyber Security:
      - Intro: cyber-security/Intro.md
  - Career Development:
      - Projects: "Career Development/projects.md"
      - Me: "Career Development/me.md"
  - Links: links.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.inlinehilite

plugins:
  - search
extra_css:
  - styles/extra.css
